### ISSUE TITLE
https://docs.onux.com/en-US/Developers/JavaScript-PP/Altitude-MVC

### ISSUE THREAD

**Issue by s0kil** [onux/altitude#1]
```
Error: /home/onux/onux2/jspp/views/docs.ejs:29
    27| <div class="docs">
    28| 	<div class="container-fluid">
 >> 29| 		<%- include("../../docs/" + page + ".html") %>
    30| 	</div>
    31| </div>
    32| 

ENOENT: no such file or directory, open '/home/onux/onux2/docs/Developers/JavaScript-PP/Altitude-MVC.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync [as fileLoader] (fs.js:397:15)
    at fileLoader (/home/onux/onux2/node_modules/ejs/lib/ejs.js:220:18)
    at handleCache (/home/onux/onux2/node_modules/ejs/lib/ejs.js:179:16)
    at includeFile (/home/onux/onux2/node_modules/ejs/lib/ejs.js:239:10)
    at include (/home/onux/onux2/node_modules/ejs/lib/ejs.js:553:16)
    at eval (eval at <anonymous> (/home/onux/onux2/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:76:17)
    at returnedFn (/home/onux/onux2/node_modules/ejs/lib/ejs.js:555:17)
    at tryHandleCache (/home/onux/onux2/node_modules/ejs/lib/ejs.js:203:34)
```

**Comment by rogerpoon** [comment]
We need more context. What steps can we take to reproduce this bug?

**Comment by s0kil** [comment]
I tried to visit this link https://docs.onux.com/en-US/Developers/JavaScript-PP/Altitude-MVC and the error shown above was thrown.

![screenshot from 2018-06-01 20-41-42](https://user-images.githubusercontent.com/24403355/40868597-54f24da8-65dc-11e8-963c-f4bb8cb5b40c.png)

**Comment by s0kil** [comment]
Turns out this Is the correct link https://docs.onux.com/en-US/Developers/JavaScript-PP/Libraries/Altitude-MVC

Don't Remember how I got to this link https://docs.onux.com/en-US/Developers/JavaScript-PP/Altitude-MVC

**Comment by s0kil** [comment]
@rogerpoon Does JS++ Have A Community Forum?

**Comment by rogerpoon** [comment]
Yes, you may have had an older version of the project as it was fixed in [this commit](https://github.com/onux/altitude/commit/7ccd96d3ca7fa04b88db9d8510eb334a3ed27d27) a while back.

I've been asked about the community forum before. It might come with the website revamp. We've talked about a Discord server but nothing came about.

Closing this issue. Feel free to email or tweet if you have other queries.
